# Open Penpot and print the exact plugin steps (local MCP must already be running).
Start-Process "https://penpot.dwurdy.com"
Write-Host ""
Write-Host "=== Connect plugin (required once per session) ==="
Write-Host "1. Open your Scriptorium design FILE (not the dashboard)"
Write-Host "2. Plugins -> Load from URL"
Write-Host "3. Paste: http://localhost:4400/manifest.json"
Write-Host "4. Run the plugin -> Connect to MCP server -> status Connected"
Write-Host "5. Keep the plugin panel open"
Write-Host ""
Write-Host "Then run:  python scripts/penpot_mcp_build.py"
Write-Host "Or wait if penpot_mcp_build is already polling."
